# values.dev.yaml
tsa-pod:  # Ajoutez ce niveau pour correspondre au nom du subchart
  
  module: tsa-pod 

  chartName: tsa-pod 

  name: tsa-pod

  podManager:  # Configuration manquante
    enabled: true  # ou false selon le besoin
    ttl: 1800
    rbac:
      rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["create", "delete", "get", "list"]

  environment: dev  # ou prod

  replicas: 1

  containers:
    image: ghcr.io/miletocarmelo/tradingstrategyanalysis
    name: tsa-pod-app
    tags: latest
    ports:
      containerPort: 80 # Changed from 'http' to '80' for consistency
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    sqlite:
      enabled: false
    redis:
      enabled: false

  service:
    port: 8080
    targetPort: 80

  ingress:
    host: dev.quant-cm.com  # Moved this out of 'hosts' array for simplicity
    enabled: true  # Changed from 'enable' to 'enabled' for consistency
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx  # Added this common annotation
        nginx.ingress.kubernetes.io/rewrite-target: /$1  # If you want path rewriting
    spec:
      path: /tsa-pod
      pathType: Prefix

  configmap:
    enabled: false