trading-strategy-analysis:
  
  module: trading-strategy-analysis

  environment: dev

  replicas: 1

  containers:
    image: ghcr.io/miletocarmelo/tradingstrategyanalysis
    name: tranding-strategy-analysis
    tags: latest
    ports:
      containerPort: 80 # Changed from 'http' to '80' for consistency
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1024Mi"
        cpu: "200m"
    sqlite:
      enabled: false
    redis:
      enabled: false

  service:
    port: 80
    targetPort: 80

  ingress:
    host: dev.quant-cm.com  # Moved this out of 'hosts' array for simplicity
    enabled: true  # Changed from 'enable' to 'enabled' for consistency
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx  # Added this common annotation
        nginx.ingress.kubernetes.io/rewrite-target: /  # Changed from pathRewrite
    spec:
      path: /trading-strategy-analysis
      pathType: Prefix

  configmap:
    enabled: false