kyc-client-onboarding:
  module: kyc-client-onboarding

  replicas: 2

  containers:
    image: ghcr.io/flowbanksa/dev_kyc_client_onboarding
    name: kyc-client-onboarding
    tags: v0.1.96
    serviceAccount:
      enabled: true
      create: true
      name: kyc-client-onboarding-sa
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::967198747629:role/apps/kyc_kyc-client-onboarding-sa"
        eks.amazonaws.com/sts-regional-endpoints: "true"
    ports:
      containerPort: 8000
    resources:
      requests:
        memory: "250Mi"
        cpu: "500m"
      limits:
        memory: "250Mi"
        cpu: "500m"
    sqlite:
      enable: false
    redis:
      enable: false

  service:
    port: 8000

  ingress:
    host: cloud-uat.flowbank.com
    enable: true
    metadata:
      annotations:
        haproxy.org/path-rewrite: /kyc-client-onboarding/(.*) /\1
    spec:
      path: /kyc-client-onboarding
      pathType: Prefix

  secrets:
    type: sealedSecret #stringData, sealedSecret or data
    data:
      DB_URL: AgCVzhIq3KS/LtVU+6UWXJBxM3N7ktBH6ptWYij9qA4fTlCw6gLPIu/FLdHBzpi0khQS/oeCfF0Jaa6v+iTt1wXq59p9k2M7lZleCw7CTWlBhi9oU3SLWoWd8DFJmdL+2u6v/EhTpGWHlFokuXjQPEju7qmxOfGBWOa5l4FYw4Xrn+ESSqPM8Mnsa3IMbdD9QiU6VBuHZySSWnGAzblkj1z7+sFQQXo1lmRoY3pJEouk5sB6uQ8OJZgqu1cmT37Yrjq8zVZ65dzXKjd+9zm9d/wtmna5rmEMkrpTYasa6xC6MbxDJP9PC7EoJ5xIT6LEKOFb/pwiFz62FqM7k9+2Hy8lH0/hz/kmAy6Y1XEO1rkGWXAHATHqme2+ho8q5yEyKP8PGH8i4THO3HRGFiFNGGqbe0QhthD0qf+en1H2Pu/uouB5QFNoTXJe9+ugPS5937/KPyoGFC7IkdaL9KOk0FT5UaDE2I6ccVoKy3ki/TwBhwEhP2Yi5VTS2AYgyTy3gFlPb/CTbXdViMkEpQOkrcywdQTY9mHqek0wcpR56dXF1UsZ9zdINsLFIKPfjmB2F4rrVqy8h2FV3nW7+0WV/Y5sogbGlkdUhFbd8gHf2k3MX/k7HwIwhR24BtEchDd8nZxbuJ1kN5budO9qpw7Om9MoVNZCkTaKqIPFnvMOnCtRwiixV5+hoVgrIIarZ/RpiMkXdZJYJjV0JDv+avBTmAhCBKfeKs7hVpbgaFoFwb7RerQUBO7CeI1XrggdVJwx7C3ydLX44FswG3gfUkw1+YDXBPP8klcs/R+Mqnpr5PBj/Vv7QihVAJqi4mUrI3ybEkPOa7C20QNCxT6CJ0nrvMDe5WLDFoxJJUDgRw==
      GOOGLE_API_KEY: AgBXRYrLmqKfkHWdX5arIfhM3ZmAxoXu4uoHqg0i7loMV0iUqiHBVe131IvSjyc0Qks0zEVOZRd7Ev3GV/w4N0+nXDMgxsxUL3BdY8ptC+Vb8pFlJeExkFpRGnZAxmtSTDh+xqRv0hBY5yFUOUmtb5L7dmmNyPnfq/bV/1+mpyhTSIkkHyiurP3ul+Uv8gBiv33izJmFg6akLzNx+BZGVAfhkW8TXK8e9FQxd0oK5Kh8kTF/By34BB0Gq//5WKSk7hVUiokmrME9ilvT9bAg1Z3Q9zxvySvPP4EsRPaBb0Q6vTAIZYMripH1kn4+dBgm8C9OP7VbWpKNF2UqYO5UWoOHKiAscGznf6OQYegwHTjsBOKl2I8ijPguq/gjn9cu2IBs50nZQ9Ov/jjRgoZklYJtV2mcu/N9hUty0FhVRuynyle4OPDSrVcVuVLuKiW9PPdPLhh3VM+331rtHguhkSJwH6AbKin68wwyypgm0j2GrEKD6Z+yOnypzfINd6XrjgzNmDPrKA6wjzmrNdlO3vS43WlVMlw/mpM9H1gHRwv0TAyiC4JY4BOcjMcDh39MGQp4nmSwxtTthMcE+e1jE/5wGoHh3DdcButwfBD9xHsy0xJBwrWDBIcF3P4JNTKEmkYLL+vSuXomNBRs9JkIFwk2PXZdNcnrzjE2y5YcmCSZFud/EMuJKs2n5F3Qcq+d4bCG0eTyMFYr2p3aoqzDwPwSWBKFnxTUVH7pzFWck99o2TvhxNIj2nY=
      INTRUM_JWT: AgBiZ9opspqXTIrcD3DD3vaRNGKGaA+VWBmflKPy/B2ohw/btPgw7Qysk3C83e8f7Sd5iWzURNI9P+sjmKsQxDsesTZ5iJB2v5bPjfZ0aJfbzN9gEcuNWNvRlc6Mu/QlP0+DyPMeyFiunW31exnC0Dbggl+IxGKmdySQAy/ChsJelVT2coDcTKYy0yZ2zTbFRDD3r/liUMOoaYg6U3D5CfQ5N/vPO8IurRa2qcgU+UPXClIbrsMS15VVcQyTIHT0qNOv1LQ4ny3lopiu5XhSpKn7E6sI0oLEzd4cCE9FkKB9fGmpzjG0mF0XCJ/uSDyIJNyFpB/buz2S2ff9UI+5fk1sxdG+rjsaNV9t1LV922aIyAj8IuvRi1iGtGzKxkyUYkqO6uV1wTAYZx/pRF5xzg0ardI6T1DqDWYkgO0WB5aRyxkRH8RsIBUPxBYpGOgXMr+BljB+PXddzjf0IZHh04XC7fmr+BbxLEH8ChYSH9gq10uIpz6TNOlFQqNO7ckxAj5204RkVWnAmePFuj1WJfWHG6U3ppPGY1VCo4u5K5aiH/F+kjQ84jPg8LzAwSftacDnqYNgipc0Dzqr/cVm1+o2SZ0OK5NWfUxI1p4tuogKJDOSpvJcO9A/BYBatvpq0/uUApvOQAfhawbDcRns+YK+AomDmCMc2QGKrOEAb8B3PqcvYhNj3fpB9TrPkUMuMHTHQRPXYQKOl8AN5Wai9OZRzgD+lgmYHPSLW39mOMY504aLhTrqInL5tBsZnZ5mRD7lCGu6mSU9Dnw8Yb8xwH9T0Rfg6zuIudKcGALZzCUhHxTKbnJZJqcXPvWStl1HpCQpWhp5sPaJ2Q/HHhRnnas2prQrQDNzAXvKY1Pzc8E86fSghzGyUdCO6qQrsPzT6byovp7Wra/6IqBk6PT/PYZlQN07Ab7cHZ3A/zkA5vivIZ5bWaib9jMoIeIt0YTJvNI84QnRMkBliD0hWLgGvf45KnnAcPSJuMEANBaf2oU1MDO7upYMlIpMzsMmYBQgLikMAG6SqvGUH0d+Sqrpt1iqaTLcOFsVkopfgduSj3UaRKClZSB3B0M7w1jAhbNtSIC3+sJUOEnArXDoWHQEfYM=
      INTRUM_PASSWORD: AgAeUKQy8PFkrpLqlClODeK7LY0xxmln+iEz1jDdp/aoDLAQurr/HF1M4kGlOL3pQe4ulkAUMC4mRXsMlR19uLGjRDkoHoai0bRaDhvtfC/Zi9sfRs0OHikfVCjFd+vh3cJCx/YeqOqPHOAQAUQwxm50X/O6tKyEA3cS22VP1fjIkzrvC39IOWJaCB6R12AclCvNp7fiMn2551/R346xY5dR9I1QNBWK6ytCrtrunb+Md84f4cVAd3CP+7UNRV21ZN4NbeAOGkyPgG/981tkqscz6mJFuwcMzKemh7GJAhcr12+9AhC4NGpAw1CddmaFQkrUF37MvY+OfaBO2n209+9mu0CT5yFjFzd7bYFwynHt0Dwlj7fZBRvHr93arx5IQhcaIQ7daZKOIEwIeNWV+JCSymaHj5N5jgsrAtNRZzXep9R5gxkSwaqJhZROQL54sOgz6j3jnnNHf+ummPB7mVTPweBm8ZMKawCmh5gXFBmVN4rFfcPwpNljFJsv82+BJbzuVtj/AWIO3MeLR8AheRnBmFwL4daaamlS9scn/V4/jINCucs1fgONWptZx+2dq3uSX2JMQRRqlpQPvYet1jQMIPX3RQ8DJLGSLw/wQ/LM0vHg2aYaDZpDv/4KMBT+5/Sw0VxpNcihpmnKn04qpm9T77OEXtfPyciutBqlPI66y2qkKsVTTNV2KO8OdOwbFEBUBVWGwR6zvEvnwdQZXKbyuEViKA==
      OKTA_CLIENT_SECRET: AgDoXWzRXvKVO853mHam3tjhkf0djfrB2YnohYrn9Ex0GHKd4WUmL43D8TRoobi80GrM0B//ZCTszoCRKOMRMVQMwmo/vDgMjCNEVXT9E/73ighjtT3gxqfkAS1+R6AdaDbwzmjcIydLg6XRXZiueHtsZcOJ1ymb9RMQ4KgfTKDS4pp1vST3Lpp+arpSwzqRO1ah31FdLIWpysgH9RNIahPLLsqhO7g0TrzNyQRuaJ/uwIJA0WkqLqmmhkffRSv7PWCNKU2IRf8NRjT/EIhZ4Wow91gKtWp5PtoA/+ERgWEZaiYdeL64EjbhhPtyuDBJ+wp5XnCqYaQfsoGIy+3QzKBOC2SAevWKr7zNy2SBYks+Iq3X9NkjTS+6Kjft3eVbDxvRoZBA3g3SI34sNttGgNHIUwT2R6F0B4io0a+LFTgnmHe+PX03kgCX9v66Rsd0VSQLzETDQRbgfj15P1+ZCVFe3ptgbLA50s8+Vt5/VcK3Q/iWL1RUAmtuir0PMm8KjyVh7GxG92KpCVhiASuXu6N4e31KJEI+n04zZZkbLnWrIlRzdHKOy/z0C+qwLx1U8f8rCWVPleAE7k1wvW5Dc9/gc7HeOiwGooeDUL44ByrUJj5slBA6o6FO7pS5AgK8N8Ulr9UOq5UEYU1L1InkexAqG90405D7P2eQDKDTEzj7GWVmgvp+NbD/EKkhcai5xmecPqlp0+JxqSBg37/ZXXKNlwiSgqqPDS0vHlSFNtTLiijOTS4qBBdQDeFrheVzSmk0QoTknMG1A3cV7HEeTvgD
      PEGA_PASSWORD: AgCe6MuSeHcnRz8m+MEq3FTxAeswVEUSxNQlsP1RFekiMcx2wrq9fBxISTzCShuRN2/txCVSbXBuAw7WWHR9Mjc/JOOkkwXHmQmTrMmvw9p2ihyi6SuSHZy0p2Le4nZWTzF0/oVmu5YyVg+1Q9ALBX9OnLH7NaoYOOMnNVVhJFHk1eEZsBs+hUwnQVctWNPEhMykOWGyRNVpNwqr5EPoo1wg7I19uAske+Ey9eFN4KGR+QF/zoo8RE7rxOW5tAzQe2AMBaN9Th45qlyWL0QpQ8X4GQFwyUW+0UriX1p5r1FLTCjFlJUWoaHcHqtMMSoIhnWbjhYJE0+nE/tBZizpCgoe0qvGmQt87M/OjBpqihsj/Pn2uKjvg/ebnE+rOquQ0ryEUoFCTqMHb/L0qzHCmSjaXsazi7Y/5gXx1m3RcZ/edfjVlY0Qnj6/g63EiXwSruiq+aGeRZRooP6P8nJ1vmWqxGMTazX4DaNjqExN6aP6DD7GzjSAv48jIHf5jf5shWPP7qaYuhIx1OA6HdgieDgUyTPOIeHR2IbnI1h36F1Oe3yDLw3NHr8DUU+X6zIJKrEm66DZpzvjGcue4IrX8iGTEW/7qrEg4IzbWc6bf2VuqVDO8C57F40+jz8xLrLNtgIpYAHJrf+2MgEDxzRtTexw9MQvXX37AHnSDa2Wg5i/tPxA0utLp+rwtunymxpm7N87bGbFLxdtFCmQdSLOVWJH10LmclOmGpGcuS5C5sUk8g==
  
  configmap:
    enabled: true
    data:
      OKTA_DOMAIN: "flowbank-uat.eu.auth0.com"
      API_PORT: "8000"
      PEGA_USER: "25253149798704441241"
      PEGA_URL: "https://flbkpr-flow-st1.pega.net/prweb/api/FBCLMUTA"
      PEGA_TOKEN_URL: "https://flbkpr-flow-st1.pega.net/prweb/PRRestService/oauth2/v1/token"
      OKTA_CLIENT_ID: JMJFD88Ub3fRvKOla5wEDvouSAGYdGRr
      INTRUM_DOMAIN: https://sandbox-autoid.id-validation.ch
      INTRUM_TENANT_ID: c9ca6d4b-344f-4f3a-8ef2-fd3610abc789
      SIGNING_WEBHOOK_WORKERS: '5'
      IDENTIFICATION_WEBHOOK_WORKERS: '5'
      USE_DOCUMENTS_FROM_S3: 'true'
      AWS_S3_REGION: 'eu-central-2'
      AWS_S3_BUCKET: 'flowbank-client-legal-documents-uat'
      AWS_S3_FOLDER_PREFIX: 'flowbank_client_legal_documents_'
      FORCE_HAPPY_PATH: 'false'
      TAX_DOC_NAME: 'Tax Self-Certification.pdf'
      SIGNING_REDIRECT_SUCCESS_URL: 'https://my-pega-uat.flowbank.com/onboarding'
      SIGNING_REDIRECT_FAILED_URL: 'https://my-pega-uat.flowbank.com/onboarding'
      SIGNING_REDIRECT_REDIRECT_URL: 'https://my-pega-uat.flowbank.com/onboarding'
      SIGNING_REDIRECT_TIMEOUT_URL: 'https://my-pega-uat.flowbank.com/onboarding'
      LEGAL_DOCUMENT_LANGUAGES: 'ar,ch,en,fr,it,de,es'
      INTRUM_SUPPORTED_LANGUAGES: 'fr,de,en,it'
      TAX_DOC_TRANSLATIONS: '{"en":"Tax Self-Certification.pdf"}'
      SIGNATURE_PLACEMENT: '{"page":0,"y":5,"x":5,"width":700,"height":100,"fontName":"Arial","fontSize":10,"textVisible":true,"image":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="}'

  technicalSecret:
    type: data #stringData, sealedSecret or data
    githubSecret: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiRGViem91IiwicGFzc3dvcmQiOiJnaHBfQ2sxWEc2aDhBd0NXWjVXSjlKbDNDZlpYZmkzM3NtMnFZQVJOIiwiYXV0aCI6IlJHVmllbTkxT21kb2NGOURhekZZUnpab09FRjNRMWRhTlZkS09VcHNNME5tV2xobWFUTXpjMjB5Y1ZsQlVrND0ifX19

