kyc-client-onboarding:
  module: kyc-client-onboarding

  replicas: 2

  containers:
    image: ghcr.io/flowbanksa/dev_kyc_client_onboarding
    name: kyc-client-onboarding
    tags: v0.1.0
    ports:
      containerPort: 8080
    sqlite:
      enable: false
    redis:
      enable: false

  service:
    port: 8080

  ingress:
    host: cloud-uat.flowbank.com
    enable: true
    metadata:
      annotations:
        haproxy.org/path-rewrite: /kyc-client-onboarding/(.*) /\1
    spec:
      path: /kyc-client-onboarding
      pathType: Prefix

  secrets:
    mountPath: /app
    type: sealedSecret
    data: AgBtomLSEWBaW0R5mYCSzqFYuwcNPdUg5RmsKqYCkCVekxGFt5Z8fvOaIOIsoVAUl3SY4AdDxDZV5zaaqYDtP9iaFwMRFHVzwMGJSO2VNHNQt9OC2VLzdSeoZKaghwgqodRhrB8zujv1vgEqb3IDU/p8d39lX6drIM3qnydeggV2002VJUyyU3X4y0cXXzZfbGPDwXEUHClT1wyDPipHpJ/A6Rzh2NGy9Ve1oErSO0r/hkCssgqaGaWdQUBvqOhoK2q+Dk6NdGLwqVsXqwrvkXj+DJ4ES+UUCAJYBrYPv+VUx1iHdlkzujjQpp+qT+8RJFB43DWz3M3hrTN107WTnl7m+xUpKX6yI8IKAN0HVaLVe6oJaXGjVPIAZgyBtwNN7n3IabrIlQfnYiSGgY0QqZSYdlfC1cAB/FaCkPhBeLAdKstTZwJusNVaXjWk0W/5NilAque+1DjrwPa5b/alEcdQ/3x3n2jQEj/1QpCWstDGRfZjRv6Jn+SmZWs7a4+Ce5mDIBR/DPIDgqPDgW2L1qX0FqYVGNfEu/RIUpT2fc6pRG/xz727vBLPQ5DOrTukVZbQHKSmfvvNHTZuW4ojGuJqXx1lHBtWqTR1fX5fzc3/2cfALxI3Sy75V2pFOnSrP/Jy6DKIlJH1xHb1KGIp9cJwcI1I2bRngPFGa57f6LomNH9Vwd+Lt3Efr7inwqDukbOidHkkDSW3sCe6cwuHJxtK62pTGvcLqw4LxHV0sd6IFos9egWWD+GBah9K9F82nNQt9WGQMd32xEhVar9GL5aB0pBq6ldFKh2r95u+/nsNA+Gn+Y0dXd9XukBqitOFSYxBep0qXL0liWAo8QRPcaTQLevN5WVHK7/dlUDEeemeDeQFb5qY4wnX/wr6kpll9bq8kPJxT9kG99DEXEA9aQrGwz0BRteyCCfKFTB5P8N1uRqtGQuJYOXJ3gHMjAlhs9HoR42oNsACUAFUKJNoCrNcqCSivRNAqQ2Ub48v0fwRKOGjENGUmxA02wWfDMj5GimtiZKW86jUuRryhJ4yeNJ1xvOeLCC3KisF/1FFQIo9WceYF2RLiYBHEZehcaiM1/1L7Nr6pUNP0BWTCZqqEDW4Jrk3tpKhfJq6TzYNg5XSmMQoBtsW4MNwsCPtjCR1+D/CQ21C4i8vwpQ2GB41NGX0gAT1Qcq85v40AYVhubLezAJHEPa/jgnNiQY5A6bVvrtmsynzP/qFR8urqK84ggujhMZUBQscr2lWDahsEBwjL6gl+iVxJak9hgSbNMmhuQ6J


  technicalSecret:
    type: data #stringData, sealedSecret or data
    githubSecret: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiRGViem91IiwicGFzc3dvcmQiOiJnaHBfQ2sxWEc2aDhBd0NXWjVXSjlKbDNDZlpYZmkzM3NtMnFZQVJOIiwiYXV0aCI6IlJHVmllbTkxT21kb2NGOURhekZZUnpab09FRjNRMWRhTlZkS09VcHNNME5tV2xobWFUTXpjMjB5Y1ZsQlVrND0ifX19
