kyc-client-onboarding:
  module: kyc-client-onboarding

  replicas: 2

  containers:
    image: ghcr.io/flowbanksa/dev_kyc_client_onboarding
    name: kyc-client-onboarding
    tags: v0.1.0
    ports:
      containerPort: 8080
    sqlite:
      enable: false
    redis:
      enable: false

  service:
    port: 8080

  ingress:
    host: cloud-uat.flowbank.com
    enable: true
    metadata:
      annotations:
        haproxy.org/path-rewrite: /kyc-client-onboarding/(.*) /\1
    spec:
      path: /kyc-client-onboarding
      pathType: Prefix

  secrets:
    mountPath: /app
    type: sealedSecret
    data: AgBvzmEkV/U6adD+eqXBPSMoT0Vq7jpyrQ//J9tPVT4Bf0hYHyccie2DfddwHL5MYBVY//m/sOb8u7Er+7k2HtQcFeCDCkbnAahv47VqYySjVbY/EFWJ1tl9ZcqYbHvbnt1u+w8xIE+d13uMClrevIG3DFbifBBh2rzbwLk6+YvxQdLy3udyOX3bs387awj5B2hZZ4qWM8qTtbU1DUPRfmP+Ftwl12sXrfS9gkb6DXmVkGmHSJ3pzJ/kS3jlsKXOY0gRl2MuMnhoPlD77fCSOVIImplTH6hg1uvMQn3gTDjEj2BL1ABMXDSA//OD2iDQ2vt2hTVqdPcd36RNNS5YRue2K8Dr/PoN0DiiIu+d+LV6lR4Js2G5FwFELj0/qBXNNm9IF9p3522Mt8OHFxVkIVbvlzGBDfVrrVS672SDTeG8A7y58MZtCwELGRQCpx6ZgCjCvg0OJ4sUgYHV68aknCTybs11UnfZ741v9V1x15hGp6/n6TYxj8RzTAOkov8mI51hhSTE9FWmRvZyXpKpYJ9SJVdCvs3bXZDiq/fZjFUbMEmezYbT5vDh0k7FpD44QEIs3BWkAvuMWqtZ7HcE52oMxw5+PWtVQy8YP7rP/3eYAc1Rvr4eUDLZg/j+I+IpN5jkGyamr9sDsdRtpGP5BRpLurfcybXzBDilqPG21FX1zrPDLgJduDJXpVer2Jm66p0E5xE/NtjNSMcgmPZwAkcRLWpmd8ZS1bFYLDgPYDqs2sHT7apBaBk/3AFFg/vhbfn2DwvALIpN43/e1YsKb5ta1qW8mDEILNEHtNoemR8NYDvkLP+KQTIIpiRruhnMs3/kuW+lf+C0RVWIhEOjCg9SXZBBkOqJAxHsSH+6aO9hrP4tdiqTVLVT+AvoR6K16iprEdGybjNqDHuydioik+m4yFXjP3qEMLV/H5kv7+WVQWNOCra91ifhT0PxI1zIgXSWgVfdF6HdCEg+HoClo688sxkUTN5gyP2JcP0xhQD+Dx34Sw2WCTKlN7QwZQNDUqNoO5Inm8USIvYIdEQl0lnGIwcyqla5cyCUstsASd50JcxNu1EPaOc3X+p24vMcD0RDNOSH/mIYcJeczXeg1OsmCYnTWYbmlZBkRpLNGKS7eP5HT1m67UheAXcX0tsK7moOqzA6pbR1tsoZ6wiGckP4YTUPwQx1bYqfotu01gb4hc2OLS29gXDrLmzQeys/w+5B/IzjKIbuf8YEJej7qsdVYQ/avVrru/vfGFGVypmhbrlrVFk7qLeq52UWzgBRasjg


  technicalSecret:
    type: data #stringData, sealedSecret or data
    githubSecret: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiRGViem91IiwicGFzc3dvcmQiOiJnaHBfQ2sxWEc2aDhBd0NXWjVXSjlKbDNDZlpYZmkzM3NtMnFZQVJOIiwiYXV0aCI6IlJHVmllbTkxT21kb2NGOURhekZZUnpab09FRjNRMWRhTlZkS09VcHNNME5tV2xobWFUTXpjMjB5Y1ZsQlVrND0ifX19
